%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 2 
use_gps: 0
use_compass: 0
use_pressure: 1

imu_topic: "/bluerov2/imu"
image0_topic: "/bluerov2/bluerov2/cameraleft/camera_image"
image1_topic: "/bluerov2/bluerov2/cameraright/camera_image"
gps_topic: "/gps"
pressure_topic: "/bluerov2/pressure"
compass_topic: "/bluerov2/compass"

output_path: "/home/nvidia/vins/output/"

cam0_calib: "cam0_pinhole.yaml"
cam1_calib: "cam1_pinhole.yaml"
image_width: 768
image_height: 492
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 0.0,-1.0, 0.0, 0.0,
          -1.0, 0.0, 0.0, 0.1,
           0.0, 0.0,-1.0,-0.2,
           0, 0, 0, 1]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 0.0,-1.0, 0.0, 0.0,
          -1.0, 0.0, 0.0,-0.1,
           0.0, 0.0,-1.0,-0.2,
           0, 0, 0, 1]



#Multiple thread support
multiple_thread: 1
use_gpu: 1
use_gpu_acc_flow: 1

#feature traker paprameters
max_cnt: 150           # max feature number in feature tracking
min_dist: 10           # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 0           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy
epipolar_tolerance: 5.0

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 5.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.004      # accelerometer measurement noise standard deviation. 0.00294 
gyr_n: 0.0003394     # gyroscope measurement noise standard deviation. 0.000175     
acc_w: 0.00001      # accelerometer bias random work noise standard deviation.  
gyr_w: 0.00001     # gyroscope bias random work noise standard deviation.     
g_norm: 9.80     # gravity magnitude

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/nvidia/vins/output/pose_graph/" # save and load path
save_image: 0                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
